version: "3.8"
services:
  web:
    build: .
    ports:
      - 8080:80
      - 6001:6001
    environment:
      PM_APP_URL: http://localhost
      PM_APP_PORT: 80
      PM_BROADCASTER_PORT: 6001
      PM_ADMIN_MAIL: test@rossonet.com
      PM_ADMIN_PASSWORD: test123
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DBNAME: pmos
      MYSQL_USERNAME: pmos_user
      MYSQL_PASSWORD: password123
      MYSQL_ROOT_PASSWORD: pass_root123
      REDIS_HOST: redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - storage:/code/pm4/storage
    links:
      - redis
      - mysql 
    depends_on:
      - mysql
      - redis 
  redis:
    image: redis
    restart: always
  mysql:
    image: mariadb:10.9.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass_root123 
      MYSQL_DATABASE: pmos
      MYSQL_USER: pmos_user
      MYSQL_PASSWORD: password123
    volumes:
      - database:/var/lib/mysql
volumes:
  database:
  storage:
